package GUI;

import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import java.util.List;
import model.*;
import util.*;
import GUI.*;
import GUI.ManagerDashboard;
import GUI.ResetPassword;
import GUI.StaffDashboard;


public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    public LoginGUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);

        passwordErrorLabel.setPreferredSize(new java.awt.Dimension(416, 20));
        emailFormatLabel.setPreferredSize(new java.awt.Dimension(416, 20));
        
        emailOrPhoneField.getDocument().addDocumentListener(new SimpleListener(this::validateEmailFormat));
        passwordErrorLabel.setForeground(Color.RED);
      
    }

        private void handleLogin() {
            String input = emailOrPhoneField.getText().trim();
            String password = new String(passwordField.getPassword());
            passwordErrorLabel.setText("");

            if (input.isEmpty() || password.isEmpty()) {
                passwordErrorLabel.setText("Email/Phone and Password cannot be empty.");
                return;
            }

            List<User> allUsers = FileStorage.getAllUsers();
            User matchedUser = null;

            for (User u : allUsers) {   
                if (u.getEmail().equalsIgnoreCase(input) || u.getPhone().equals(input)) {
                    matchedUser = u;
                    break;
                }
            }


            if (matchedUser == null) {
                int option = JOptionPane.showConfirmDialog(
                        this,
                        "Account not found. Do you want to register?",
                        "Account Not Found",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (option == JOptionPane.YES_OPTION) {
                    dispose();
                    new RegisterCustomer().setVisible(true);
                }
                return;
            }

            // Try both original and trimmed comparison
            if (!matchedUser.getPassword().equals(password) && 
                !matchedUser.getPassword().trim().equals(password.trim())) {
                passwordErrorLabel.setText("Incorrect password.");
                passwordField.setText("");
                return;
            }

            // Successful login
            JOptionPane.showMessageDialog(this, "Login successful!");
            dispose();

            matchedUser.displayDashboard();
        }


        private class SimpleListener implements javax.swing.event.DocumentListener {
            private final Runnable action;

            public SimpleListener(Runnable action) {
                this.action = action;
            }

            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                action.run();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                action.run();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                action.run();
            }
        }

        private void validateEmailFormat() {
            String input = emailOrPhoneField.getText().trim();
            if (!input.matches("^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$") && !input.matches("^\\d{10,11}$")) {
                emailFormatLabel.setText("Invalid email or phone format");
         } else {
                emailFormatLabel.setText("");
            }
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jToggleButton1 = new javax.swing.JToggleButton();
        headLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        emailOrPhoneField = new javax.swing.JTextField();
        emailOrHpLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordErrorLabel = new javax.swing.JLabel();
        emailFormatLabel = new javax.swing.JLabel();
        showPasswordCheck = new javax.swing.JCheckBox();
        forgotPasswordButton = new javax.swing.JButton();
        loginButton1 = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(239, 249, 255));
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        headLabel.setBackground(new java.awt.Color(234, 253, 253));
        headLabel.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        headLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLabel.setText("APU Medical Centre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 205, 0, 0);
        getContentPane().add(headLabel, gridBagConstraints);

        registerButton.setBackground(new java.awt.Color(153, 153, 255));
        registerButton.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 73, 97, 0);
        getContentPane().add(registerButton, gridBagConstraints);

        emailOrPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailOrPhoneFieldActionPerformed(evt);
            }
        });

        emailOrHpLabel.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        emailOrHpLabel.setText("Email or Phone Number : ");

        pwdLabel.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        pwdLabel.setText("Password: ");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        passwordErrorLabel.setFont(new java.awt.Font("Perpetua", 1, 12)); // NOI18N
        passwordErrorLabel.setForeground(new java.awt.Color(255, 0, 51));
        passwordErrorLabel.setText(" ");

        emailFormatLabel.setFont(new java.awt.Font("Perpetua", 1, 12)); // NOI18N
        emailFormatLabel.setForeground(new java.awt.Color(255, 0, 51));
        emailFormatLabel.setText(" ");

        showPasswordCheck.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        showPasswordCheck.setText("Show Password");
        showPasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckActionPerformed(evt);
            }
        });

        forgotPasswordButton.setBackground(new java.awt.Color(153, 153, 153));
        forgotPasswordButton.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        forgotPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        forgotPasswordButton.setText("Forgot Password ?");
        forgotPasswordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(emailOrHpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(emailOrPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(emailFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(showPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(passwordErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pwdLabel)
                        .addGap(127, 127, 127)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailOrHpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailOrPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(emailFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(pwdLabel))
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPasswordCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(passwordErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 28, 0, 48);
        getContentPane().add(jPanel1, gridBagConstraints);

        loginButton1.setBackground(new java.awt.Color(102, 153, 255));
        loginButton1.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        loginButton1.setForeground(new java.awt.Color(255, 255, 255));
        loginButton1.setText("Login");
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 253, 97, 0);
        getContentPane().add(loginButton1, gridBagConstraints);

        exitButton.setBackground(new java.awt.Color(255, 102, 102));
        exitButton.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 61, 97, 48);
        getContentPane().add(exitButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailOrPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailOrPhoneFieldActionPerformed
        validateEmailFormat();
    }//GEN-LAST:event_emailOrPhoneFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        dispose();
        new RegisterCustomer().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordButtonActionPerformed
        dispose();
        new ResetPassword();
    }//GEN-LAST:event_forgotPasswordButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void showPasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckActionPerformed
            char echo = showPasswordCheck.isSelected() ? (char) 0 : '●';
            passwordField.setEchoChar(echo);
    }//GEN-LAST:event_showPasswordCheckActionPerformed

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        handleLogin();
    }//GEN-LAST:event_loginButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailFormatLabel;
    private javax.swing.JLabel emailOrHpLabel;
    private javax.swing.JTextField emailOrPhoneField;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JLabel headLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton loginButton1;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox showPasswordCheck;
    // End of variables declaration//GEN-END:variables
}
