package util;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import java.awt.Color;
import java.io.FileOutputStream;
import java.util.Date;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class PDFReportWriter {

    public static void writeReportPdf(String filePath, String title, String html, String managerName)
            throws Exception {
        Document doc = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(filePath));
            doc.open();

            // ====== Header ======
            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Font subFont   = new Font(Font.HELVETICA, 11, Font.NORMAL);

            String reportId = UUID.randomUUID().toString().substring(0, 8);

            doc.add(new Paragraph("APU Medical Centre - " + title, titleFont));
            doc.add(new Paragraph("Jalan Teknology 5, Technology Park Malaysia, Bukit Jalil, Kuala Lumpur", subFont));
            doc.add(new Paragraph("Generated on: " + new Date(), subFont));
            doc.add(new Paragraph("Report ID: " + reportId, subFont));
            doc.add(new Paragraph("Generated by: " + managerName, subFont));
            doc.add(new Paragraph(" "));

            // ====== Extract ALL <table> blocks ======
            Pattern tablePattern = Pattern.compile("(?is)<table.*?</table>");
            Matcher matcher = tablePattern.matcher(html);

            while (matcher.find()) {
                String tableHtml = matcher.group();

                // Parse rows inside this table
                String[] rows = tableHtml.split("(?i)<tr>");
                PdfPTable pdfTable = null;

                for (String row : rows) {
                    if (!row.contains("<td") && !row.contains("<th")) continue;

                    int cols = row.split("(?i)<td|<th").length - 1;
                    if (pdfTable == null) {
                        pdfTable = new PdfPTable(cols);
                        pdfTable.setWidthPercentage(100);
                    }

                    String[] cells = row.split("(?i)<td|<th");
                    for (String c : cells) {
                        if (!c.contains(">")) continue;
                        String val = c.substring(c.indexOf(">") + 1)
                                      .replaceAll("(?i)</td>|</th>", "")
                                      .replaceAll("<[^>]+>", "")
                                      .trim();

                        PdfPCell cell = new PdfPCell(new Phrase(val, new Font(Font.HELVETICA, 11)));
                        cell.setPadding(5);

                        if (c.startsWith("th")) {
                            cell.setBackgroundColor(new Color(240, 240, 240));
                            cell.setPhrase(new Phrase(val, new Font(Font.HELVETICA, 11, Font.BOLD)));
                        }
                        pdfTable.addCell(cell);
                    }
                }
                if (pdfTable != null) {
                    doc.add(pdfTable);
                    doc.add(new Paragraph(" ")); // spacing between tables
                }
            }

            // ====== Extract <p class='summary'> ======
            if (html.contains("class='summary'")) {
                String summary = html.split("(?i)<p class='summary'>")[1];
                summary = summary.replaceAll("(?i)</p>.*", "")
                                 .replaceAll("<[^>]+>", "")
                                 .trim();

                doc.add(new Paragraph(" "));
                doc.add(new Paragraph(summary, new Font(Font.HELVETICA, 11)));
            }

        } finally {
            doc.close(); //always close to avoid corruption
        }
    }
}
