
package GUI;

import java.awt.Color;
import java.awt.Font;
import model.Staff;

public class StaffDashboard extends javax.swing.JFrame {
    
    private final Staff loggedInStaff; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboard.class.getName());


    public StaffDashboard(Staff staff) {
        this.loggedInStaff = staff;
        initComponents();
        jLabel2.setText("Welcome, " + staff.getName());
        setSize(800, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        //Panel
        jPanel2.setBackground(Color.WHITE);
        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        
        //Label
        jLabel1.setForeground(Color.WHITE);
        jLabel1.setFont(new Font("Perpetua", Font.PLAIN, 35));
        jLabel2.setForeground(Color.black);
        jLabel2.setFont(new Font("Perpetua", Font.BOLD, 15));
        
        
        //Buttons
        crudCustomerBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        crudCustomerBtn.setForeground(Color.WHITE);
        crudCustomerBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        bookingBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        bookingBtn.setForeground(Color.WHITE);
        bookingBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        emergencyBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        emergencyBtn.setForeground(Color.WHITE);
        emergencyBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        assignApptBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        assignApptBtn.setForeground(Color.WHITE);
        assignApptBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        paymentBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        paymentBtn.setForeground(Color.WHITE);
        paymentBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        editProfileBtn.setBackground(new java.awt.Color(72, 103, 150)); 
        editProfileBtn.setForeground(Color.WHITE);
        editProfileBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        logoutBtn.setBackground(new java.awt.Color(0, 51, 102)); 
        logoutBtn.setForeground(Color.WHITE);
        logoutBtn.setFont(new Font("Perpetua", Font.BOLD, 17));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crudCustomerBtn = new javax.swing.JButton();
        bookingBtn = new javax.swing.JButton();
        emergencyBtn = new javax.swing.JButton();
        assignApptBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        editProfileBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APU Medical Centre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        crudCustomerBtn.setText("Manage Customers");
        crudCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudCustomerBtnActionPerformed(evt);
            }
        });

        bookingBtn.setText("Manage Walk-in Booking");
        bookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBtnActionPerformed(evt);
            }
        });

        emergencyBtn.setText("Emergency Appointment");
        emergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyBtnActionPerformed(evt);
            }
        });

        assignApptBtn.setText("Assign Appointment to Doctor");
        assignApptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignApptBtnActionPerformed(evt);
            }
        });

        paymentBtn.setText("Collect payment & Generate Receipt");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        editProfileBtn.setText("Edit Profile");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Welcome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crudCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emergencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignApptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(editProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crudCustomerBtn)
                .addGap(18, 18, 18)
                .addComponent(bookingBtn)
                .addGap(18, 18, 18)
                .addComponent(emergencyBtn)
                .addGap(18, 18, 18)
                .addComponent(assignApptBtn)
                .addGap(18, 18, 18)
                .addComponent(paymentBtn)
                .addGap(18, 18, 18)
                .addComponent(editProfileBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(logoutBtn)
                .addGap(0, 157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudCustomerBtnActionPerformed
        dispose();
        new CrudCustomerPage(loggedInStaff).setVisible(true);
    }//GEN-LAST:event_crudCustomerBtnActionPerformed

    private void bookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBtnActionPerformed
        dispose();
        new AppointmentFormForStaff(loggedInStaff).setVisible(true);
    }//GEN-LAST:event_bookingBtnActionPerformed

    private void emergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyBtnActionPerformed
        dispose();
        new EmergencyAppointmentForm(loggedInStaff).setVisible(true);
    }//GEN-LAST:event_emergencyBtnActionPerformed

    private void assignApptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignApptBtnActionPerformed
        dispose();
        new AssignAppointmentPage(loggedInStaff).setVisible(true);
    }//GEN-LAST:event_assignApptBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        dispose();
        new CollectPaymentPage(loggedInStaff).setVisible(true);
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
    new GenericEditProfileFrame1(loggedInStaff, this).setVisible(true);        
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
            javax.swing.JOptionPane.showMessageDialog(
                    null,
                    "Logout successful. Thank you, " + loggedInStaff.getName() + "!",
                    "Logout",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
          new LoginGUI().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed
    
         public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        // Create a mock manager for testing until login is ready
        Staff mockStaff = new Staff(
            "Mixue",           // id
            "MickeyMouse",            // name
            "Male",                // gender
            "MickeyMouse@Staff.com", // email
            "012789456",           // phone
            "Mickey_123",            // password
            "21/11/1979"           // dob (date of birth)
        );
        new StaffDashboard(mockStaff).setVisible(true);
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignApptBtn;
    private javax.swing.JButton bookingBtn;
    private javax.swing.JButton crudCustomerBtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JButton emergencyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton paymentBtn;
    // End of variables declaration//GEN-END:variables
}
